export const projects = [
  {
    name: 'UDR',
    image: '/udr.png',
    url: 'https://udr.vercel.app/',
    repo: 'https://github.com/Patag1/UDR',
    desc: 'Ultimate Dev Roadmap, or UDR, aims to compile a curated list of useful resources for developers, with the purpose of helping them in their learning and professional growth.',
    techs: [
      'Tailwind CSS',
      'Typescript',
      'React',
      'Next.js',
      'Zustand',
      'Node.js',
      'Prisma',
      'PostgreSQL',
    ],
    status: false,
    ud: false,
  },
  {
    name: 'VS cosmética',
    image: '/vsnc.png',
    url: '',
    repo: '',
    desc: 'A full-stack e-commerce made for my sister\'s cosmetic sales. It will create/update/delete users, differentiate between client and admin users, add/remove products to/from cart, make an order, process payments, create/update/delete products and track and display statistics into a dashboard with the retrieved data',
    techs: [
      'Tailwind CSS',
      'Typescript',
      'React',
      'Next.js',
      'Zustand',
      'Next-Auth',
      'Node.js',
      'Prisma',
      'PostgreSQL',
    ],
    status: false,
    ud: true,
  },
  {
    name: 'Newsletter',
    image: '/news.png',
    url: '',
    repo: 'https://github.com/Patag1/newsletter',
    desc: 'A project I developed as inspiration to an API that I found about news. Keeps people updated on latest news on tech. Users can create an account, like/unlike and save/unsave news, change language of the fetched news and more.',
    techs: [
      'Tailwind CSS',
      'Typescript',
      'React',
      'Next.js',
      'Zustand',
      'Next-Auth',
      'Node.js',
      'Prisma',
      'PostgreSQL',
    ],
    status: false,
    ud: true,
  },
  {
    name: 'Brick',
    image: '/brick.png',
    url: '',
    repo: '',
    desc: 'Brick is a groundbreaking startup initiative that revolutionizes the way you connect with skilled professionals with a different approach to client/customer support, implementing awesome new features.',
    techs: [
      'Tailwind CSS',
      'Typescript',
      'React',
      'Next.js',
      'Zustand',
      'Next-Auth',
      'Node.js',
      'Prisma',
      'PostgreSQL',
    ],
    status: true,
    ud: true,
  },
  // { name: 'DIYed', url: '', repo: '', desc: 'Brick is a groundbreaking startup initiative that revolutionizes the way you connect with skilled professionals with a different approach to client/customer support, implementing awesome new features. Under development.', status: true },
]
